// frontend/src/lib/components/LatencyTrendChart.svelte
<script lang="ts">
  import { AreaChart } from "layerchart";
  import { curveCatmullRom } from "d3-shape";
  import { scaleTime } from "d3-scale";
  import type { DailyStatsDto } from "$lib/api.js";

  interface Props {
    data: DailyStatsDto[];
    metric?: "avg" | "min" | "max";
    height?: number;
    class?: string;
  }

  let { data, metric = "avg", height = 128, class: className = "" }: Props = $props();

  const chartData = $derived(
    data
      .map((d) => ({
        date: new Date(d.timestamp * 1000),
        value:
          metric === "avg" ? d.avgLatencyMs
          : metric === "min" ? d.minLatencyMs
          : d.maxLatencyMs,
      }))
      .filter((d) => d.value !== null && d.value > 0) as { date: Date; value: number }[]
  );
</script>

<div class={className} style="height: {height}px;">
  {#if chartData.length >= 2}
    <AreaChart
      data={chartData}
      x="date"
      xScale={scaleTime()}
      y="value"
      yDomain={[0, null]}
      yNice={true}
      axis="x"
      grid={false}
      series={[{ key: "value", label: "Latency", color: "hsl(var(--chart-1))" }]}
      props={{
        area: { curve: curveCatmullRom, "fill-opacity": 0.3 },
        xAxis: {
          format: (d: Date) =>
            d.toLocaleDateString(undefined, { month: "short", day: "numeric" }),
        },
      }}
    />
  {:else}
    <div class="flex items-center justify-center h-full text-muted-foreground text-sm">
      {chartData.length === 1 ? "Not enough data for trend (need at least 2 days)" : "No latency data available"}
    </div>
  {/if}
</div>

// apps/web/src/components/LatencyTrendChart.tsx
"use client";

import {
  AreaChart,
  Area,
  XAxis,
  YAxis,
  Tooltip,
  ResponsiveContainer,
} from "recharts";
import type { DailyStatsDto } from "@/src/lib/api";
import { formatLatency } from "@/src/lib/utils";

interface Props {
  data: DailyStatsDto[];
  metric?: "avg" | "min" | "max";
  height?: number;
}

export function LatencyTrendChart({ data, metric = "avg", height = 128 }: Props) {
  const chartData = data
    .map((d) => ({
      date: new Date(d.timestamp * 1000).toLocaleDateString(undefined, {
        month: "short",
        day: "numeric",
      }),
      value:
        metric === "avg" ? d.avgLatencyMs : metric === "min" ? d.minLatencyMs : d.maxLatencyMs,
    }))
    .filter((d) => d.value !== null && d.value > 0) as { date: string; value: number }[];

  if (chartData.length < 2) {
    return (
      <div className="flex items-center justify-center text-muted-foreground text-sm" style={{ height }}>
        {chartData.length === 1
          ? "Not enough data for trend (need at least 2 days)"
          : "No latency data available"}
      </div>
    );
  }

  return (
    <ResponsiveContainer width="100%" height={height}>
      <AreaChart data={chartData} margin={{ top: 4, right: 4, bottom: 0, left: 0 }}>
        <defs>
          <linearGradient id="latencyGradient" x1="0" y1="0" x2="0" y2="1">
            <stop offset="5%" stopColor="#3b82f6" stopOpacity={0.35} />
            <stop offset="95%" stopColor="#3b82f6" stopOpacity={0} />
          </linearGradient>
        </defs>
        <XAxis
          dataKey="date"
          tick={{ fontSize: 11, fill: "currentColor", opacity: 0.5 }}
          tickLine={false}
          axisLine={false}
          interval="preserveStartEnd"
        />
        <YAxis hide domain={[0, "auto"]} />
        <Tooltip
          formatter={(v) => [formatLatency(Number(v)), "Latency"]}
          contentStyle={{ fontSize: 12 }}
        />
        <Area
          type="monotone"
          dataKey="value"
          stroke="#3b82f6"
          fill="url(#latencyGradient)"
          strokeWidth={2}
          dot={false}
        />
      </AreaChart>
    </ResponsiveContainer>
  );
}
