// apps/web/components/Nav.tsx
import Link from "next/link";

export function Nav() {
  return (
    <header className="border-b bg-background/80 backdrop-blur sticky top-0 z-40">
      <div className="mx-auto max-w-3xl px-4 h-14 flex items-center justify-between">
        <Link href="/" className="font-semibold text-base tracking-tight">
          Piro
        </Link>
        <nav className="flex items-center gap-4 text-sm">
          <Link
            href="/admin"
            className="text-muted-foreground hover:text-foreground transition-colors"
          >
            Admin
          </Link>
        </nav>
      </div>
    </header>
  );
}

// frontend/src/lib/components/Nav.svelte
<script lang="ts">
  import type { UserDto } from "$lib/api";

  let { user }: { user?: UserDto } = $props();
</script>

<header class="border-b bg-background/80 backdrop-blur sticky top-0 z-40">
  <div class="mx-auto max-w-3xl px-4 h-14 flex items-center justify-between">
    <a href="/" class="font-semibold text-base tracking-tight">Piro</a>
    <nav class="flex items-center gap-4 text-sm">
      {#if user}
        <a href="/admin" class="text-muted-foreground hover:text-foreground transition-colors">Admin</a>
        <form method="POST" action="/auth/sign-out">
          <button type="submit" class="text-muted-foreground hover:text-foreground transition-colors">
            Sign out
          </button>
        </form>
      {:else}
        <a href="/auth/sign-in" class="text-muted-foreground hover:text-foreground transition-colors">Sign in</a>
      {/if}
    </nav>
  </div>
</header>
